name: databases

services:
  # adminer:
  #   image: adminer
  #   container_name: Adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mysql
  #     - postgres

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./config/phpmyadmin/custom.ini:/usr/local/etc/php/conf.d/custom.ini # Linux is case sensitive, so table name cases should be consistent!
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_USER: "${MASTER_USERNAME}"
      PMA_PASSWORD: "${MASTER_PASSWORD}"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: MySQL
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./data/mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql # Linux is case sensitive, so table name cases should be consistent!
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MASTER_PASSWORD}"

  postgres:
    image: postgres:alpine
    container_name: PostgreSQL
    restart: always
    ports:
      - 5432:5432
    volumes:
      # - ./data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data # Linux is case sensitive, so table name cases should be consistent!
    environment:
      POSTGRES_USER: "${MASTER_USERNAME}"
      POSTGRES_PASSWORD: "${MASTER_PASSWORD}"

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: MSSQL
  #   restart: always
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - mssql-data:/var/opt/mssql
  #   environment:
  #     MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
  #     ACCEPT_EULA: "Y" # Accept the SQL Server End-User License Agreement
  #     MSSQL_PID: "Developer" # Specify the SQL Server edition

  # mssql:
  #   build:
  #     context: ./config/mssql
  #     dockerfile: Dockerfile
  #   container_name: MSSQL
  #   restart: always
  #   ports:
  #     - "1433:1433"
  #   volumes:
  #     - mssql-data:/var/opt/mssql
  #   environment:
  #     MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
  #     ACCEPT_EULA: "Y" # Accept the SQL Server End-User License Agreement
  #     MSSQL_PID: "Developer" # Specify the SQL Server edition

volumes:
  mysql-data:
  postgres-data:
  mssql-data:
