version: "3.9"

name: ubuntu

services:

  ubuntu:
    tty: true
    container_name: Ubuntu
    restart: always
    build:
      context: ./config/ubuntu
      dockerfile: Dockerfile
    ports:
      # - 81:81 # phpMyAdmin
      - 80:80 # PHP
      - 443:443 # PHP
      # - 8080:8080 # Java
      # - 3000:3000 # Node.js
      # - 3306:3306 # MySQL
    volumes:
      # Serve app folder to the server
      # - ./app/node.js:/app
      # - ./app/php:/var/www/html
      - ./config/letsencrypt:/etc/letsencrypt
      - ./config/nginx/conf.d/reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
      - ./config/nginx/conf.d/app1.conf:/etc/nginx/conf.d/app1.conf
      - ./config/nginx/conf.d/app2.conf:/etc/nginx/conf.d/app2.conf
      # - ./config/nginx/conf.d/ssl.conf:/etc/nginx/sites-available/default
      # - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # - ./config/php/overrides.ini:/etc/php/8.1/fpm/conf.d/overrides.ini
    # entrypoint: [ "/bin/sh", "-c" ]
    # Escape environmental variables (e.g. NVM_DIR) in the command using an extra $
    # command:
    #   - |
    #     echo "Command 1"
    #     echo "Command 2"
    #     echo "Command 3"
