version: "3.9"

name: ubuntu

services:
  ubuntu:
    tty: true
    image: ubuntu
    container_name: Ubuntu
    restart: always
    # ports:
    #   - 3000:3000
    volumes:
      - ./app:/home
    # environment:
    #   - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true" # Allow Jenkins to build local folders with a Jenkins file
