version: "3.9"

name: Apps

services:
  nginx:
    container_name: Nginx
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    tty: true # Keep the container "always running". Prevent <Container> exited with code 0 error
