version: "3.9"

name: development

services:

  php:
    container_name: PHP-Apache
    restart: always
    build:
      context: ./config/apache2
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      # Serve app folder to the server
      - ./app/php:/var/www/html/
      # - D:/xampp/htdocs:/var/www/html/
      - ./config/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
  # node.js:
  #   # image: node:alpine
  #   container_name: Node.js
  #   restart: always
  #   build:
  #     context: ./config/node.js
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #     - 5000:5000
  #   volumes:
  #     - ./app/node.js:/app
  #   tty: true # Keep the container "always running". Prevent <Container> exited with code 0 error

  # Spring Boot
  # java:
  #   image: maven:3.8.5-jdk-8
  #   container_name: Java-Maven
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./app/java/test:/usr/local/bin
  #     - ./app/java/test/entrypoint.sh:/usr/local/bin/mvn-entrypoint.sh
  #====================
  # entrypoint.sh
  # #!/bin/sh
  # You can set anything you need here before starting the spring boot application
  # cd /usr/local/bin
  # mvn install
  # mvn spring-boot:run
  #====================