version: "3.9"

name: Terraform

services:
  terraform:
    image: hashicorp/terraform
    container_name: Terraform
    restart: always
    build:
      context: ./docker/terraform
      dockerfile: Dockerfile
    volumes:
      - ./terraform:/var/terraform
      - ~/.aws:/root/.aws
      - ~/.ssh:/root/.ssh
    tty: true # Keep the container "always running". Prevent <Container> exited with code 0 error
