name: development

services:
  php:
    container_name: PHP-Apache
    restart: always
    build:
      context: ./config/apache2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini
      - ./app/laravel/api:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    working_dir: /var/www/html
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        echo 'Starting laravel app...'
        composer install --no-interaction --optimize-autoloader
        php artisan serve --host=0.0.0.0 --port=8000
