version: "3.9"

name: development

services:
  php:
    container_name: PHP-Apache
    restart: always
    build:
      context: ./config/apache2
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./config/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini # Override PHP settings
      - ./app/laravel/api:/var/www/html/ # Serve laravel app
