version: "3.9"

name: Server

services:
  nginx:
    container_name: Nginx
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./app/html:/usr/share/nginx
      - ./docker/nginx/conf.d/reverse-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/conf.d/app1.conf:/etc/nginx/conf.d/app1.conf
      - ./docker/nginx/conf.d/app2.conf:/etc/nginx/conf.d/app2.conf
    tty: true # Keep the container "always running". Prevent <Container> exited with code 0 error
