version: "3.9"

name: Server

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80 # http://
      - 443:443 # https:// (SSL)
    volumes:
      # - ./app/html:/usr/share/nginx # FROM: nginx
      - ./app/html:/var/www/html # FROM: ubuntu
      - ./config/letsencrypt:/etc/letsencrypt
      - ./config/nginx/conf.d/reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
      - ./config/nginx/conf.d/app1.conf:/etc/nginx/conf.d/app1.conf
      - ./config/nginx/conf.d/app2.conf:/etc/nginx/conf.d/app2.conf
