version: "3.9"

name: Databases

services:

  adminer:
    image: adminer
    container_name: Adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - postgres

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: "${PMA_HOST}"
      PMA_USER: "${PMA_USER}"
      PMA_PASSWORD: "${PMA_PASSWORD}"
    depends_on:
      - mysql

  # php:
  #   container_name: PHP-Apache
  #   restart: always
  #   build:
  #     context: ./docker/apache
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   volumes:
  #     # Serve app folder to the server
  #     # - ./app/php:/var/www/html/
  #     - D:/xampp/htdocs:/var/www/html/
  #     - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini

  mysql:
    image: mysql:latest
    container_name: MySQL
    restart: always
    ports:
      - 3306:3306
    volumes:
      # - ./data/mysql:/var/lib/mysql
      - mysql-data:/var/lib/mysql # Linux is case sensitive, so table name cases should be consistent!
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  postgres:
    image: postgres:alpine
    container_name: PostgreSQL
    restart: always
    ports:
      - 5432:5432
    volumes:
      # - ./data/postgres:/var/lib/postgresql/data
      - postgres-data:/var/lib/postgresql/data # Linux is case sensitive, so table name cases should be consistent!
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

volumes:
  mysql-data:
  postgres-data:
