version: "3.9"

name: CI/CD

services:
  jenkins:
    # 2.347
    image: jenkins/jenkins:lts
    container_name: Jenkins
    restart: always
    ports:
      - 8080:8080
      - 5000:5000
      - 3000:3000
    volumes:
      - ./app/node.js/webpack:/var/jenkins_home/app/webpack
      - jenkins-data:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true" # Allow Jenkins to build local folders with a Jenkins file

volumes:
  jenkins-data:
